! dudon_natte.scl
!
Natté series from 28 to 151, pentatonic sequence out of 7 consecutive tones 
 12
!
 86/57
 65/57
 98/57
 74/57
 151/114
 2/1
 86/57
 65/57
 98/57
 74/57
 112/57
 2/1
! White keys play the seven tones (with two commas 148:151 and 56:57)
! Black keys play only plain pentatonic 43:49:57:65:74
! Natté triple eq-b sequence (Dudon), known also as "Meta-Slendro" (Wilson)
! x^3 - x =  x^5 - x^4 = 1 (x = 1.3247179572447 or 486.822277651 c.)
